export const sampleProjects = [
  {
    id: 1,
    name: "Parròquia Santa Maria",
    location: "Vilanova i la Geltrú",
    status: "En restauración",
    lat: 41.2233,
    lng: 1.7250,
  },
  {
    id: 2,
    name: "Parròquia Sant Antoni Abat",
    location: "Vilanova del Camí",
    status: "En uso",
    lat: 41.5736,
    lng: 1.6350,
  },
  {
    id: 3,
    name: "Parròquia Sant Pere",
    location: "Sant Pere de Ribes",
    status: "Estudio técnico",
    lat: 41.2570,
    lng: 1.7792,
  },
  {
    id: 4,
    name: "Parròquia Sant Sadurní",
    location: "Sant Sadurní d'Anoia",
    status: "Mantenimiento pendiente",
    lat: 41.4290,
    lng: 1.7861,
  },
  {
    id: 5,
    name: "Parròquia Sant Esteve",
    location: "Castelldefels",
    status: "Restauración finalizada",
    lat: 41.2800,
    lng: 1.9765,
  },
  {
    id: 6,
    name: "Parròquia Mare de Déu de Montserrat",
    location: "El Prat de Llobregat",
    status: "En restauración",
    lat: 41.3275,
    lng: 2.0945,
  },
  {
    id: 7,
    name: "Parròquia Sant Joan Baptista",
    location: "Vilafranca del Penedès",
    status: "Intervención urgente",
    lat: 41.3443,
    lng: 1.6994,
  },
  {
    id: 8,
    name: "Parròquia Santa Magdalena",
    location: "Esparreguera",
    status: "Inspección programada",
    lat: 41.5389,
    lng: 1.8700,
  },
  {
    id: 9,
    name: "Parròquia Sant Miquel",
    location: "Molins de Rei",
    status: "En uso",
    lat: 41.4143,
    lng: 2.0169,
  },
  {
    id: 10,
    name: "Parròquia Sant Llorenç",
    location: "Sant Feliu de Llobregat",
    status: "En restauración",
    lat: 41.3809,
    lng: 2.0464,
  }
];


